In [1]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dhrut\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [5]:
df.shape

(20800, 5)

In [6]:
df.isna().sum() #total of null items in each column

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
df = df.fillna(' ')

In [8]:
df.isna().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [9]:
df['content'] = df['author'] + " " + df['title']

In [10]:
df

,id,title,author,text,label,content
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1,Darrell Lucus House Dem Aide: We Didn’t Even S...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0,"Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo..."
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1,Consortiumnews.com Why the Truth Might Get You...
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1,Jessica Purkiss 15 Civilians Killed In Single ...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1,Howard Portnoy Iranian woman jailed for fictio...
...,...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0,Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0,"Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma..."
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0,Michael J. de la Merced and Rachel Abrams Macy...
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1,"Alex Ansary NATO, Russia To Hold Parallel Exer..."
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1,David Swanson What Keeps the F-35 Alive

In [11]:
df['content'][20796]

'Benjamin Hoffman N.F.L. Playoffs: Schedule, Matchups and Odds - The New York Times'

In [12]:
ps = PorterStemmer()

def stemming(content):
    stemmedContent = re.sub('[^a-zA-Z]', ' ', content) #replace any characte thats not a letter with a space
    stemmedContent = stemmedContent.lower() #make lower case
    stemmedContent = stemmedContent.split() #split
    stemmedContent = [ps.stem(word) for word in stemmedContent if not word in stopwords.words('english')]
    stemmedContent = ' '.join(stemmedContent)
    return stemmedContent

In [13]:
df['content'] = df['content'].apply(stemming)

In [14]:
df['content']

0        darrel lucu hous dem aid even see comey letter...
1        daniel j flynn flynn hillari clinton big woman...
2                   consortiumnew com truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoy iranian woman jail fiction unpu...
                               ...
20795    jerom hudson rapper trump poster child white s...
20796    benjamin hoffman n f l playoff schedul matchup...
20797    michael j de la merc rachel abram maci said re...
20798    alex ansari nato russia hold parallel exercis ...
20799                            david swanson keep f aliv
Name: content, Length: 20800, dtype: object

In [29]:
X = df['content'].values
y = df['label'].values

In [31]:
vector = TfidfVectorizer()
vector.fit(X)
X = vector.transform(X)

In [33]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 210687 stored elements and shape (20800, 17128)>
  Coords	Values
  (0, 267)	0.2701012497770876
  (0, 2483)	0.36765196867972083
  (0, 2959)	0.24684501285337127
  (0, 3600)	0.3598939188262558
  (0, 3792)	0.27053324808454915
  (0, 4973)	0.23331696690935097
  (0, 7005)	0.2187416908935914
  (0, 7692)	0.24785219520671598
  (0, 8630)	0.2921251408704368
  (0, 8909)	0.36359638063260746
  (0, 13473)	0.2565896679337956
  (0, 15686)	0.2848506356272864
  (1, 1497)	0.2939891562094648
  (1, 1894)	0.15521974226349364
  (1, 2223)	0.3827320386859759
  (1, 2813)	0.19094574062359204
  (1, 3568)	0.26373768806048464
  (1, 5503)	0.7143299355715573
  (1, 6816)	0.1904660198296849
  (1, 16799)	0.30071745655510157
  (2, 2943)	0.3179886800654691
  (2, 3103)	0.46097489583229645
  (2, 5389)	0.3866530551182615
  (2, 5968)	0.3474613386728292
  (2, 9620)	0.49351492943649944
  :	:
  (20797, 3643)	0.2115550061362374
  (20797, 7042)	0.21799048897828685
  (20797, 8364)	0.22322585870464115
  (20797, 8988)	0.36160868928090795
  (20797, 9518)	0.29542040034203126
  (20797, 9588)	0.17455348025522197
  (20797, 10306)	0.08038079000566466
  (20797, 12138)	0.24778257724396505
  (20797, 12344)	0.27263457663336677
  (20797, 13122)	0.24825263521976057
  (20797, 14967)	0.3115945315488075
  (20797, 15295)	0.08159261204402356
  (20797, 16996)	0.08315655906109998
  (20798, 350)	0.2844693781907258
  (20798, 588)	0.3112141524638974
  (20798, 1125)	0.4460515589182237
  (20798, 5032)	0.40837014502395297
  (20798, 6889)	0.3249628569429943
  (20798, 10177)	0.31924963701870285
  (20798, 11052)	0.4460515589182237
  (20798, 13046)	0.2236326748827061
  (20799, 377)	0.5677577267055112
  (20799, 3623)	0.37927626273066584
  (20799, 8036)	0.45983893273780013
  (20799, 14852)	0.5677577267055112

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.32, stratify = y, random_state = 2)

In [43]:
X_train.shape

(14144, 17128)

In [45]:
X_test.shape

(6656, 17128)

In [47]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [49]:
train_y_pred = model.predict(X_train)
print("train accuracy: ", accuracy_score(train_y_pred, y_train))

train accuracy:  0.9850113122171946

In [51]:
test_y_pred = model.predict(X_test)
print("test accuracy: ", accuracy_score(test_y_pred, y_test))

test accuracy:  0.9740084134615384

In [61]:
input_data = X_test[100]
prediction = model.predict(input_data)
if prediction[0] == 1:
    print('Fake News!')
else:
    print('Real News!')

Real News!

In [53]:
df['content'][10]

'aaron klein obama organ action partner soro link indivis disrupt trump agenda'